---
- name: Install zabbix-agent
  hosts: all
  vars:
    zabbix_port: 10050
    zabbix_server_ip: 121.42.166.245
  tasks:
  - name: Add zabbix repo
    yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present
  - name: Install zabbix-agent and libselinux-python
    yum: name={{ item }} state=present
    with_items:
     - zabbix-agent
     - libselinux-python

  - name: Copy zabbix_agent.conf
    template: src=/etc/ansible/roles/zabbix/zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf

  - name: Modify Hostname in zabbix_agent.conf 
    lineinfile: dest=/etc/zabbix/zabbix_agentd.conf create=yes state=present regexp="^Hostname=" 
                line="Hostname={{ inventory_hostname }}"


  - iptables: chain=INPUT source={{ zabbix_server_ip }} protocol=tcp destination_port={{ zabbix_port }} jump=ACCEPT

  - name: Start zabbix-agent and enable
    service: name=zabbix-agent state=started enabled=yes

  - name: Save iptables rules
    command: service iptables save
